package proto;

public enum TipoMensaje {
	MENSAJE_CONEXION,
	MENSAJE_CONFIRMACION_CONEXION,
	MENSAJE_LISTA_USUARIOS,
	MENSAJE_CONFIRMACION_LISTA_USUARIOS,
	MENSAJE_PEDIR_FICHERO,
	MENSAJE_EMITIR_FICHERO,
	MENSAJE_PREPARADO_CLIENTESERVIDOR,
	MENSAJE_PREPARADO_SERVIDORCLIENTE,
	MENSAJE_CERRAR_CONEXION,
	MENSAJE_CONFIRMACION_CERRAR_CONEXION,
	MENSAJE_ACTUALIZAR;
}
